# -- user should edit --
appPath <- "/path/to/application"
dataPath <- "/path/to/data"
filename <- "filename"

# -- some file names --
bulkloader <- paste0(appPath, "/bulkloader.yaml")
rawfile <- paste0(dataPath, "/", filename, "_raw.csv")
tidyfile <- paste0(dataPath, "/", filename, "_tidy.csv")

# -- execute system commands to download the raw data --
download <- TRUE
if(download) {
  shellCmd <- paste0(
    "appcfg.py download_data ",
    "--config_file=", bulkloader, " ",
    "--filename=", rawfile, " ",
    "--kind=DataObject ",
    appPath
  )
  system(command = shellCmd)
}

# -- remove the autogenerated files --
cleanup <- TRUE
if(cleanup) {
  bulkfiles <- grep("bulkloader-", list.files(dataPath), 
                    value = TRUE, fixed= TRUE)
  for(bf in bulkfiles) {
    file.remove(paste0(dataPath,"/",bf))
  }
}

# -- parse the raw data into something nicer --
makenice <- TRUE
if(makenice) {
  
  # raw data
  raw <- read.csv(file=rawfile, header=TRUE, stringsAsFactors=FALSE)
  
  # create tidy from 1st subject
  nsubj <- dim(raw)[1]
  tidy <- read.csv(text=raw[1,1]) 
  tidy$subj_id <- 1
  tidy$timestamp <- raw[1,2]
  if(is.null(tidy$gender)) tidy$gender <- NA
  
  # if there are multiple subjects, iterate
  if(nsubj>1) {
    for( i in 2:nsubj) {
      tmp <- read.csv(text=raw[i,1])
      tmp$subj_id <- i
      tmp$timestamp <- raw[i,2]
      if(is.null(tmp$gender)) tmp$gender <- NA
      tidy <- rbind(tidy, tmp) 
    }
  }
  
  # reorder columns because I'm like that
  leftvars <- c("subj_id", "timestamp", "gender",
                "age", "language", "country", "turkcode")
  rightvars <- setdiff(names(tidy), leftvars)
  tidy <- tidy[, c(leftvars, rightvars)]
  
  # save
  write.csv(tidy, file=tidyfile, row.names = FALSE)
  
}

